add support for filter expr
Mr-Pine/ilias-grader pull request #2
Opened 2024-11-01 20:09 UTC by weisbrja

2024-11-01 21:15 UTC, Mr-Pine requested changes

2024-11-01 21:15 UTC, Mr-Pine commented on src/feedback.rs
> +                                info!("Skipped uploading {}", target_filename);
I think this would be better as `debug!` as potentially many skipped files would hide actually uploaded ones

2024-11-01 21:15 UTC, Mr-Pine commented on src/feedback.rs
> +                            };
Since this is repeated pretty much exactly below and has some more logic now I think it makes sense to extract this innermost block to its own function (which it arguably did before as well...)

2024-11-01 21:15 UTC, Mr-Pine commented on src/feedback.rs
> +
While I don't really see extracting this as necessary here as `upload_feedback` is only called once, this general pattern is very common in ilias-rs. As I'm not very happy with my current implementation there I'm planning to move to https://crates.io/crates/lazy_static, so I would suggest using this here as well (or not extracting the regex into a static variable)

2024-11-01 23:37 UTC, weisbrja commented on src/feedback.rs
> +                            };
I honestly have no idea what that function would represent, like as a concept. It has some really mixed responsibilities, like filtering the file, appending the suffix, uploading the file.

2024-11-02 00:11 UTC, Mr-Pine approved these changes

2024-11-02 00:18 UTC, merged